AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Thumb Nailer - Thumbnail generator
Resources:
#------------------------- LAMBDA FUNCTION ------------------------
  ThumbNailerLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./deploy.zip
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 300
      Environment:
        Variables:
          destinationBucket: !Ref DestinationBucket
      Events:
        OriginBucketFileCreate:
          Type: S3
          Properties:
            Bucket: !Ref OriginBucket
            Events: s3:ObjectCreated:*
      Policies:
        - AmazonS3FullAccess
        - AmazonSQSFullAccess
  FailingLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./deploy.zip
      Handler: badIndex.handler
      Runtime: nodejs6.10
      Timeout: 3
    Events:
      OriginBucketFileCreate:
        Type: S3
        Properties:
          Bucket: !Ref OriginBucket
          Events: s3:ObjectCreated:*
    Policies:
      - AmazonSQSFullAccess
#---------------------------- S3 Buckets ---------------------------
  OriginBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "adesmarais-nhjs-origin-bucket"
  DestinationBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "adesmarais-nhjs-destination-bucket"
#----------------------------- SQS DLQ -----------------------------
  ThumbNailerDeadLetterQueue:
    Type: "AWS::SQS::Queue"